### ISSUE TITLE
H decay mode parameter name

### ISSUE THREAD

**Issue by beyerja** [yradkhorrami/HdecayMode#1]
Hi @yradkhorrami ,
I was just looking at this code out of curiosity and found that you accidentally write the H->other flag onto the H->ccbar flag here:
https://github.com/yradkhorrami/HdecayMode/blob/a8b560980a9e0dff7a98b24d5ed604bc6aec77e6/src/HdecayMode.cc#L105

**Comment by yradkhorrami** [comment]
Hi @beyerja ,
Thanks for reporting the issue. I corrected it and also added second ISR 4-momentum to output collection parameters.
